import "./globals.css";
import Navbar from "@/components/Navbar";
import { VariantProvider } from "@/context/VariantContext";

export const metadata = {
    title: "Smg Fantasy",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <VariantProvider>
                    <Navbar />
                    {children}
                </VariantProvider>
            </body>
        </html>
    );
}