import "./globals.css";
import Navbar from "@/components/Navbar";
import { ContextProvider } from "@/context/AppContext";

export const metadata = {
    title: "Smg Fantasy",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <ContextProvider>
                    <Navbar />
                    {children}
                </ContextProvider>
            </body>
        </html>
    );
}